---
  - name: Installing apt-key
    apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
    tags: ["node"]

  - name: Import the NodeSource GPG key into apt
    apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
    tags: ["node"]

  - name: Add NodeSource deb repository
    apt_repository: repo='deb {{ nodejs.repository }} {{ ansible_distribution_release }} main' state=present
    tags: ["node"]

  - name: Add NodeSource deb-src repository
    apt_repository: repo='deb-src {{ nodejs.repository }} {{ ansible_distribution_release }} main' state=present
    tags: ["node"]

  - name: Install Node.js
    apt: pkg=nodejs state=latest update_cache=yes
    tags: ["node"]
