---
  - name: Add Elasticsearch apt key
    apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present
    tags: ["elasticsearch"]

  - name: Add Elasticsearch repository
    apt_repository: repo='deb http://packages.elastic.co/elasticsearch/2.x/debian stable main' state=present update_cache=yes
    tags: ["elasticsearch"]

  - name: Install Elasticsearch
    apt: pkg=elasticsearch state=present
    tags: ["elasticsearch"]

  - name: Configure Elasticsearch
    lineinfile: dest=/etc/elasticsearch/elasticsearch.yml regexp="{{ item.regexp }}" line="{{ item.line }}" state=present
    with_items:
      - { regexp: 'network\.host', line: 'network.host: localhost' }
    tags: ["elasticsearch"]

  - name: "Ensure Elasticsearch is {{ elasticsearch.start | ternary('started','stopped') }}"
    service: name=elasticsearch state={{ elasticsearch.start | ternary('restarted','stopped') }} enabled={{ elasticsearch.service_enabled }}
    tags: ["elasticsearch"]
