---
  - name: "Create Solid folder"
    file:
      path: "{{ playbook_dir }}{{ node_solid_server_folder_path_redhat }}"
      state: directory
      mode: 0775
      recurse: yes
    become: true
    become_method: sudo
    tags: ["solid","get_node_solid_server"]

  - name: "Pull solid from git"
    git:
      repo: "{{ node_solid_server_url }}"
      dest: "{{ node_solid_server_folder_path_redhat }}"
    become: true
    become_method: sudo
    tags: ["solid","get_node_solid_server"]
