---
- connection: local
  hosts: 127.0.0.1
  become: true
  become_method: sudo
  vars:
    rabbitmq_version: 3.0.2-1

  tasks:
  - name: ensure python-software-properties is installed
    apt: pkg=python-software-properties state=installed
  - name: add rabbitmq repository key
    sudo: yes
    apt_key: >-
      url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
      state=present
  - name: add rabbitmq repository
    sudo: yes
    copy: src=rabbitmq.list dest=/etc/apt/sources.list.d/ backup=yes
  - name: install rabbitmq server
    sudo: yes
    apt: 
      name: rabbitmq-server
      force: yes
  - name: enable rabbitmq plugins
    rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing,rabbitmq_federation state=enabled
    notify:
    - restart rabbitmq
  - name: ensure vhost /test is present
    rabbitmq_vhost: name=/test state=present

  handlers:
  - name: restart rabbitmq
    service: name=rabbitmq-server state=restarted
