---
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
    become: true
    become_method: sudo
    ignore_errors: True
    tags: ["general","gdpr"]

  - name: Update and upgrade dist
    apt:
      upgrade: dist
    become: true
    become_method: sudo
    ignore_errors: True
    tags: ["general","gdpr"]
