---
  - name: "Create Solid folder"
    file:
      path: "{{ solid_folder_path_debian }}"
      state: directory
      mode: 0775
      recurse: yes
    become: true
    become_method: sudo
    tags: ["solid"]

  - name: "Pull solid from git"
    git:
      repo: "{{ solid_server_url }}"
      dest: "{{ solid_folder_path_debian }}"
    become: true
    become_method: sudo
    tags: ["solid"]
