---
  - name: "Create Solid folder"
    file:
      path: "{{ solid_folder_path_debian }}"
      state: directory
      mode: 0775
      recurse: yes
    become: true
    become_method: sudo
    tags: ["solid","get_solid"]

  - name: "Pull solid from git"
    git:
      repo: "{{ solid_server_url }}"
      dest: "{{ solid_folder_path_debian }}"
    become: true
    become_method: sudo
    tags: ["solid","get_solid"]
    
  - name: "Replace config.json-default file"
    copy:
      src: config.json-default
      dest: /home/georgemanakanatas/Solid/SolidAnsible/test/
      owner: root
      group: root
    become: true
    become_method: sudo
    tags: ["solid","get_solid"]
 
  - name: "replace Dockerfile"
    copy:
      src: Dockerfile
      dest: /home/georgemanakanatas/Solid/SolidAnsible/test/
      owner: root
      group: root
    become: true
    become_method: sudo
    tags: ["solid","get_solid"]
